# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-02-05 22:04
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('risk', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Risks',
            new_name='Risk',
        ),
    ]
