# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-02-05 22:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('risk', '0005_auto_20180205_2234'),
    ]

    operations = [
        migrations.RenameField(
            model_name='risk',
            old_name='risk_name',
            new_name='name',
        ),
        migrations.AddField(
            model_name='risk',
            name='slug',
            field=models.SlugField(default=1),
            preserve_default=False,
        ),
    ]
