# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-02-05 13:06
from __future__ import unicode_literals

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='InsuranceCalculator',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('type', models.CharField(choices=[('third', 'Third Party'), ('compressive', 'Compressive')], max_length=15)),
            ],
        ),
    ]
