# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-02-05 22:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calculator', '0011_auto_20180205_2227'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vehicle',
            name='cubic_capacity',
            field=models.CharField(choices=[('Above_2000', 'Above 2000'), ('up_to_1600', 'Up to 1600'), ('1600_to_2000', '1600 to 2000')], max_length=50),
        ),
    ]
