# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-02-05 22:46
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('risk', '0006_auto_20180205_2240'),
        ('calculator', '0013_auto_20180205_2240'),
    ]

    operations = [
        migrations.AddField(
            model_name='vehicle',
            name='risk',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='risk.Risk'),
            preserve_default=False,
        ),
    ]
