# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-02-05 22:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calculator', '0014_vehicle_risk'),
    ]

    operations = [
        migrations.AddField(
            model_name='vehicle',
            name='number_of_seats',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='vehicle',
            name='age',
            field=models.CharField(choices=[('five', '5 to 10 years'), ('one', '1 to 5 years'), ('above', 'Above 10 years')], max_length=50),
        ),
    ]
